/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfacesMédicos;

import Logica.LogicaMedicos.AtributosMedicos;
import Logica.LogicaMedicos.ConexionMedicos;
import Logica.LogicaMedicos.Medico;
import Logica.LogicaPrincipal.ErrorValidaciones;
import Logica.LogicaPrincipal.LogUser;
import Logica.LogicaPrincipal.Validaciones;
import interfacesPrincipales.SGP_MEDSC_admin;
import static java.awt.image.ImageObserver.HEIGHT;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Medicos extends javax.swing.JPanel {

    /**
     * Creates new form Medico
     */
    private ConexionMedicos conexion;
    private SGP_MEDSC_admin sgpMedscAdmin;
    private int confirmacion;
    private String parametro;
    private Medico medic;
    Map<String, String> dictionary;
    public Medicos() {

    }

    public Medicos(SGP_MEDSC_admin sgpMedscAdmin, LogUser user) {
        this.sgpMedscAdmin = sgpMedscAdmin;
        initComponents();
        if (!user.getUserType().equals("Medico Principal")){
            CONTAINER.setEnabledAt(2,false); 
            CONTAINER.setEnabledAt(3,false); 
        }
        conexion = new ConexionMedicos();
        dictionary = new HashMap<>();
        panelUpdate.setVisible(false);
        dictionary.put(AtributosMedicos.Especialidad.toString(), AtributosMedicos.Especialidad.getValue());
        dictionary.put(AtributosMedicos.Correo_Electrónico.toString(), AtributosMedicos.Correo_Electrónico.getValue());
        dictionary.put(AtributosMedicos.Numero_De_Celular.toString(), AtributosMedicos.Numero_De_Celular.getValue());          
        dictionary.put(AtributosMedicos.Dirección.toString(), AtributosMedicos.Dirección.getValue());        
        cmbParametro.addItem("");
        cmbParametro.addItem(AtributosMedicos.Especialidad.toString());
        cmbParametro.addItem(AtributosMedicos.Correo_Electrónico.toString());
        cmbParametro.addItem(AtributosMedicos.Dirección.toString());
        cmbParametro.addItem(AtributosMedicos.Numero_De_Celular.toString());        
    }
    private void limpiarUpdate(){
        lblActual.setText("Actual");
        lblNuevo.setText("Nuevo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CONTAINER = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedulaR = new javax.swing.JTextField();
        txtNombresR = new javax.swing.JTextField();
        txtApellidosR = new javax.swing.JTextField();
        txtNumeroR = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        txtEmailR = new javax.swing.JTextField();
        Dirección = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtCedulaC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnconsultar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEmailC = new javax.swing.JTextField();
        txtNombreC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNumeroC = new javax.swing.JTextField();
        txtEspecialidadC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDireccionC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtApellidoC = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtCedulaU = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbParametro = new javax.swing.JComboBox<>();
        btnRegistrar3 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        panelUpdate = new javax.swing.JPanel();
        lblActual = new javax.swing.JLabel();
        lblNuevo = new javax.swing.JLabel();
        txtNuevo = new javax.swing.JTextField();
        txtActual = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        DeletePanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtCedulaDelete = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnConsultarDelete = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtApellidoDelete = new javax.swing.JTextField();
        txtNameDelete = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        CONTAINER.setBackground(new java.awt.Color(255, 255, 255));
        CONTAINER.setMinimumSize(new java.awt.Dimension(577, 600));
        CONTAINER.setPreferredSize(new java.awt.Dimension(577, 600));
        CONTAINER.setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Número de Cédula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel3.setText("Correo Electrónico");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        jLabel4.setText("Nombres");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel5.setText("Apellidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        jLabel1.setText("Número Celular");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jLabel8.setText("Dirección Domiciliaria");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jLabel7.setText("Especialidad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));
        jPanel1.add(txtCedulaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 140, -1));
        jPanel1.add(txtNombresR, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 140, -1));
        jPanel1.add(txtApellidosR, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 140, -1));
        jPanel1.add(txtNumeroR, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 140, -1));

        txtEspecialidad.setToolTipText("");
        jPanel1.add(txtEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 140, -1));
        jPanel1.add(txtEmailR, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 140, -1));
        jPanel1.add(Dirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 140, -1));

        btnRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 110, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/doctor-registro.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 90, 80));

        jLabel27.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 153, 255));
        jLabel27.setText("Registrar Nuevo Médico");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 240, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/fondov4.jpg"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 680));

        CONTAINER.addTab("Registrar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel11.setText("Número de cédula");

        btnconsultar.setBackground(new java.awt.Color(51, 153, 255));
        btnconsultar.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnconsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnconsultar.setText("Consultar");
        btnconsultar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11)
                        .addGap(27, 27, 27)
                        .addComponent(txtCedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 370, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(51, 153, 255));

        jLabel12.setText("Correo electrónico");

        jLabel13.setText("Nombres");

        txtEmailC.setEditable(false);

        txtNombreC.setEditable(false);

        jLabel14.setText("Número Celular");

        jLabel16.setText("Especialidad");

        txtNumeroC.setEditable(false);

        txtEspecialidadC.setEditable(false);

        jLabel20.setText("Dirección Domiciliaria");

        txtDireccionC.setEditable(false);

        jLabel15.setText("Apellidos");

        txtApellidoC.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(txtDireccionC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEspecialidadC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtApellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtEspecialidadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtDireccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 410, 330));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/fondov4.jpg"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 680));

        CONTAINER.addTab("Consultar", jPanel2);

        updatePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel18.setText("Número de cédula");

        jLabel19.setText("Parametro");

        cmbParametro.setToolTipText("");

        btnRegistrar3.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrar3.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnRegistrar3.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar3.setText("Buscar");
        btnRegistrar3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnRegistrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCedulaU, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnRegistrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCedulaU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cmbParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        updatePanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 400, 120));

        btnActualizar.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizar.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        updatePanel.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 105, 30));

        panelUpdate.setBackground(new java.awt.Color(255, 255, 255));
        panelUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblActual.setText("Actual");

        lblNuevo.setText("Nuevo");

        txtActual.setEditable(false);

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActual)
                    .addComponent(lblNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txtActual))
                .addGap(26, 26, 26))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActual)
                    .addComponent(txtActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevo)
                    .addComponent(txtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        updatePanel.add(panelUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 430, 140));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/fondov4.jpg"))); // NOI18N
        updatePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 680));

        CONTAINER.addTab("Actualizar", updatePanel);

        DeletePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel24.setText("Número de cédula");

        btnConsultarDelete.setBackground(new java.awt.Color(51, 153, 255));
        btnConsultarDelete.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnConsultarDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarDelete.setText("Buscar");
        btnConsultarDelete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnConsultarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel24)
                        .addGap(27, 27, 27)
                        .addComponent(txtCedulaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnConsultarDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCedulaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConsultarDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DeletePanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 370, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel10.setForeground(new java.awt.Color(51, 153, 255));

        jLabel25.setText("Apellidos");

        jLabel26.setText("Nombres");

        txtApellidoDelete.setEditable(false);

        txtNameDelete.setEditable(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApellidoDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(txtNameDelete))
                .addGap(34, 34, 34))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtApellidoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DeletePanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 390, 110));

        btnDelete.setBackground(new java.awt.Color(51, 153, 255));
        btnDelete.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Eliminar");
        btnDelete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        DeletePanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 120, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/fondov4.jpg"))); // NOI18N
        DeletePanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 680));

        CONTAINER.addTab("Eliminar", DeletePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CONTAINER, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CONTAINER, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        limpiarConsulta();
        if (!txtCedulaC.getText().isBlank()){
            try {
                Validaciones.validarCedula(txtCedulaC.getText());
                if(!conexion.verificarEstaRegistrado(txtCedulaC.getText())){
                    throw new ErrorValidaciones("No existe un médico registrado con este número de cédula.");            
                }                
                medic = conexion.consultarInfoMedico(txtCedulaC.getText());
                txtNombreC.setText(medic.getNombres());
                txtApellidoC.setText(medic.getApellidos());
                txtNumeroC.setText(medic.getNumeroCelular());
                txtEspecialidadC.setText(medic.getEspecialidad());
                txtEmailC.setText(medic.getEmail());
                txtDireccionC.setText(medic.getDireccion());
                txtCedulaC.setText("");
            } catch (ErrorValidaciones | NoSuchPaddingException | NoSuchAlgorithmException | BadPaddingException | IllegalBlockSizeException | InvalidKeyException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Consulta", HEIGHT);
            } 
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese el número de cédula", "Error", HEIGHT);
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void limpiarConsulta(){
        txtNombreC.setText("");
        txtApellidoC.setText("");
        txtNumeroC.setText("");
        txtEspecialidadC.setText("");
        txtEmailC.setText("");
        txtDireccionC.setText("");        
    }
    private void btnRegistrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar3ActionPerformed
        // TODO add your handling code here:
        if (!txtCedulaU.getText().isBlank() && cmbParametro.getSelectedIndex() != -1){                 
            try {
                Validaciones.validarCedula(txtCedulaU.getText()); 
                if(!conexion.verificarEstaRegistrado(txtCedulaU.getText())){
                    throw new ErrorValidaciones("No existe un médico registrado con este número de cédula.");            
                }
                parametro = conexion.consultarParametroPorId(dictionary.get(cmbParametro.getSelectedItem().toString()), txtCedulaU.getText());
                panelUpdate.setVisible(true);
                limpiarUpdate();
                lblActual.setText(cmbParametro.getSelectedItem().toString()+" "+lblActual.getText());
                lblNuevo.setText(cmbParametro.getSelectedItem().toString()+" "+lblNuevo.getText());
                txtActual.setText(parametro);     
            } catch (SQLException |ErrorValidaciones ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", HEIGHT);
            }                  
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese todos los campos.", "Error Campos", HEIGHT);
        }
    }//GEN-LAST:event_btnRegistrar3ActionPerformed

    private void limpiarActualizacion(){
        txtCedulaU.setText("");
        cmbParametro.setSelectedIndex(-1);
        txtNuevo.setText("");
        txtActual.setText("");
    }
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            // TODO add your handling code here:
            if (txtNuevo.getText().isBlank()){
                throw new ErrorValidaciones("Ingrese el nuevo valor");
            }
            if (cmbParametro.getSelectedItem().toString().equals("Especialidad")){
                Validaciones.validarEspecialidad(txtNuevo.getText());
            }
            if (cmbParametro.getSelectedItem().toString().equals("Correo_Electrónico")){
                Validaciones.validarEmail(txtNuevo.getText());
            }
            if (cmbParametro.getSelectedItem().toString().equals("Numero_De_Celular")){
                Validaciones.validarCelular(txtNuevo.getText());
            }
            conexion.actualizarAtributo(dictionary.get(cmbParametro.getSelectedItem().toString()), txtCedulaU.getText(), txtNuevo.getText());
            JOptionPane.showMessageDialog(null, "El "+cmbParametro.getSelectedItem().toString()+" se actualizo exitosamente.", "Actualización",JOptionPane.INFORMATION_MESSAGE);
            limpiarActualizacion();
        } catch (ErrorValidaciones | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", HEIGHT);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnConsultarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDeleteActionPerformed
        // TODO add your handling code here:
        if (!txtCedulaDelete.getText().isBlank()){
            try {
                Validaciones.validarCedula(txtCedulaDelete.getText());
                if(!conexion.verificarEstaRegistrado(txtCedulaDelete.getText())){
                    throw new ErrorValidaciones("No existe un médico registrado con este número de cédula.");            
                }                
                medic = conexion.consultarInfoMedico(txtCedulaDelete.getText());
                txtNameDelete.setText(medic.getNombres());
                txtApellidoDelete.setText(medic.getApellidos());
            } catch (ErrorValidaciones | SQLException | InvalidKeyException | 
                    IllegalBlockSizeException | BadPaddingException | NoSuchAlgorithmException | NoSuchPaddingException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", HEIGHT);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese el número de cédula", "Error", HEIGHT);
        }        
    }//GEN-LAST:event_btnConsultarDeleteActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        confirmacion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar al Médico","Confirmación",JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_NO_OPTION){
            try {      
                conexion.eliminarUsuario(txtCedulaDelete.getText());
                JOptionPane.showMessageDialog(null, "Médico eliminado exitosamente.", "Eliminación", JOptionPane.INFORMATION_MESSAGE);
                limpiarEliminación();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", HEIGHT);
            }
        } 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void limpiarEliminación(){
        txtCedulaDelete.setText("");
        txtNameDelete.setText("");
        txtApellidoDelete.setText("");        
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if (!txtNombresR.getText().isBlank() && !txtApellidosR.getText().isBlank() && !txtCedulaR.getText().isBlank() &&
                !txtNumeroR.getText().isBlank() && !txtEmailR.getText().isBlank() && !txtEspecialidad.getText().isBlank() || !Dirección.getText().isBlank()){
            try {
                Validaciones.validarCedula(txtCedulaR.getText());
                if(conexion.verificarEstaRegistrado(txtCedulaR.getText())){
                    throw new ErrorValidaciones("Ya existe un médico registrado con este número de cédula.");            
                }                
                Validaciones.validarNombre(txtNombresR.getText());
                Validaciones.validarApellido(txtApellidosR.getText());
                Validaciones.validarEspecialidad(txtEspecialidad.getText());
                Validaciones.validarCelular(txtNumeroR.getText());
                Validaciones.validarDireccionDomiciliaria(Dirección.getText());
                Validaciones.validarEmail(txtEmailR.getText());
                medic = new Medico(txtCedulaR.getText(),txtNombresR.getText(),
                        txtApellidosR.getText(),txtNumeroR.getText(),txtEspecialidad.getText(),Dirección.getText(),txtEmailR.getText());
                
                confirmacion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de registrar al médico con los datos actuales?","Confirmación",JOptionPane.YES_OPTION);
                if (confirmacion == JOptionPane.YES_NO_OPTION){
                   conexion.postMedico(medic);
                  JOptionPane.showMessageDialog(null, "El Médico se ha creado exisitosamente", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                   limpiarRegistro();
                }                
            } catch (ErrorValidaciones | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Registro", HEIGHT);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese todos los campos.", "Error Campos", HEIGHT);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane CONTAINER;
    private javax.swing.JPanel DeletePanel;
    private javax.swing.JTextField Dirección;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultarDelete;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar3;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JComboBox<String> cmbParametro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblActual;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JTextField txtActual;
    private javax.swing.JTextField txtApellidoC;
    private javax.swing.JTextField txtApellidoDelete;
    private javax.swing.JTextField txtApellidosR;
    private javax.swing.JTextField txtCedulaC;
    private javax.swing.JTextField txtCedulaDelete;
    private javax.swing.JTextField txtCedulaR;
    private javax.swing.JTextField txtCedulaU;
    private javax.swing.JTextField txtDireccionC;
    private javax.swing.JTextField txtEmailC;
    private javax.swing.JTextField txtEmailR;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtEspecialidadC;
    private javax.swing.JTextField txtNameDelete;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtNombresR;
    private javax.swing.JTextField txtNuevo;
    private javax.swing.JTextField txtNumeroC;
    private javax.swing.JTextField txtNumeroR;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables

    private void limpiarRegistro() {
        txtNombresR.setText("");
        txtApellidosR.setText("");
        txtEmailR.setText("");
        txtNumeroR.setText("");
        txtCedulaR.setText("");
        txtEspecialidad.setText("");
        Dirección.setText("");
    }
}
