/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfacesCitas;

import Logica.LogicaCitas.Cita;
import Logica.LogicaCitas.ConexionCita;
import Logica.LogicaMedicos.ConexionMedicos;
import Logica.LogicaPrincipal.ErrorValidaciones;
import Logica.LogicaPrincipal.LogUser;
import Logica.LogicaPrincipal.Validaciones;
import interfacesPrincipales.SGP_MEDSC_admin;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class CitaMedica extends javax.swing.JPanel {

    /**
     * Creates new form CitaMedica
     */
    DefaultTableModel model;
    DefaultTableModel model2;
    DefaultTableModel model3;    
    DefaultTableModel model4;    
    private Cita cita;
    private String code;
    private SimpleDateFormat dateFormat;
    private SGP_MEDSC_admin sgpMedscAdmin;
    private ConexionCita conexion;
    private ConexionMedicos medicoConect;
    List<Cita> citas;
    Map<String, String> medicos;
    Map<String, String> especialidad;
    List<String> horas;
    
    public CitaMedica(SGP_MEDSC_admin sgpMedscAdmin,LogUser user){
        this.sgpMedscAdmin = sgpMedscAdmin;
        initComponents();
        medicoConect = new ConexionMedicos();
        conexion = new ConexionCita();
        if (!user.getUserType().equals("Medico Principal")){
            Contenedor.setEnabledAt(4, false);
        }
        try {
            especialidad = medicoConect.consultarEspecialidades();
            medicos = medicoConect.consultarMedicos();
            String esp = "";
            for (Map.Entry<String, String> entry : especialidad.entrySet()) {
                if (!entry.getValue().equals(esp)){
                    cbmEspecialidades.addItem(entry.getValue());
                    esp = entry.getValue();
                }
            } 
        } catch (SQLException ex) {
            System.out.println("Error carga de datos");
        }

        String columnas[] = {"Código cita","Nombre","Apellido","Fecha","Hora","Médico"};
        String columnas1[] = {"Nombre","Apellido","Fecha","Hora","Médico"};
        model = new DefaultTableModel();
        model2 = new DefaultTableModel();
        model3 = new DefaultTableModel();
        model4 = new DefaultTableModel();
        model.setColumnIdentifiers(columnas);
        model2.setColumnIdentifiers(columnas1);
        model3.setColumnIdentifiers(columnas);
        model4.setColumnIdentifiers(columnas);
        citasPacienteC.setModel(model2);
        citasPacienteU.setModel(model);
        pacienteCitaD.setModel(model3);
        Listado.setModel(model4);
        horas = new ArrayList<>();
        inicializarHorario();
    }

    private void inicializarHorario(){        
        // Agrega las horas a la lista
        horas.add("07:00");
        horas.add("07:30");
        horas.add("08:00");
        horas.add("08:30");
        horas.add("09:00");
        horas.add("09:30");
        horas.add("10:00");
        horas.add("10:30");
        horas.add("11:00");
        horas.add("11:30");
        horas.add("12:00");
        horas.add("12:30");
        horas.add("13:00");
        horas.add("13:30");
        horas.add("14:00");
        horas.add("14:30");
        horas.add("15:00");
        horas.add("15:30");
        horas.add("16:00");
        for (String hour: horas){
            cbmHora.addItem(hour);
            cbmNuevaHora.addItem(hour);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JTabbedPane();
        created = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnAgendar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txt3 = new javax.swing.JLabel();
        lblNuevo3 = new javax.swing.JLabel();
        txtNombresC = new javax.swing.JTextField();
        txtCedulaC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbmEspecialidades = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtApellidoCR = new javax.swing.JTextField();
        Fecha = new com.toedter.calendar.JCalendar();
        cbmMedicos = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbmHora = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtCedulaUpdate = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btnBuscaActualizar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lblActual = new javax.swing.JLabel();
        lblNuevo = new javax.swing.JLabel();
        txtActualHora = new javax.swing.JTextField();
        lblActual1 = new javax.swing.JLabel();
        lblActual2 = new javax.swing.JLabel();
        txtFechaActual = new javax.swing.JTextField();
        FechaNueva = new com.toedter.calendar.JDateChooser();
        cbmNuevaHora = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        citasPacienteU = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        CONSULTAR = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtCedulaConsult = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnRegistrar1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        citasPacienteC = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        LISTA = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnBuscaListado = new javax.swing.JButton();
        FechaInicio = new com.toedter.calendar.JDateChooser();
        FechaFin = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Listado = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        DELETE = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        txtCedulaDelete = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btnBuscaActualizar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pacienteCitaD = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(2042, 780));
        setPreferredSize(new java.awt.Dimension(1742, 780));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));

        created.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(1040, 830));
        jPanel10.setPreferredSize(new java.awt.Dimension(1040, 830));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgendar.setBackground(new java.awt.Color(51, 153, 255));
        btnAgendar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendar.setText("AgendarCita");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        jPanel10.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 140, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        txt3.setText("Nombres");

        lblNuevo3.setText("Apellido");
        lblNuevo3.setToolTipText("");

        jLabel10.setText("Número de Cédula Paciente");

        jLabel11.setText("Médico");

        cbmEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmEspecialidadesActionPerformed(evt);
            }
        });

        jLabel12.setText("Especialidad");

        jLabel18.setText("Hora:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNuevo3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbmMedicos, 0, 134, Short.MAX_VALUE)
                    .addComponent(cbmEspecialidades, 0, 134, Short.MAX_VALUE)
                    .addComponent(txtApellidoCR, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(txtNombresC)
                    .addComponent(txtCedulaC))
                .addGap(85, 85, 85)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(cbmHora, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbmHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt3)
                    .addComponent(txtNombresC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevo3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellidoCR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbmEspecialidades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(120, 120, 120))
        );

        jPanel10.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 970, 370));

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 153, 255));
        jLabel19.setText("Agendar Nueva Cita");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 190, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/fondov4.jpg"))); // NOI18N
        jPanel10.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 750));

        javax.swing.GroupLayout createdLayout = new javax.swing.GroupLayout(created);
        created.setLayout(createdLayout);
        createdLayout.setHorizontalGroup(
            createdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2133, Short.MAX_VALUE)
            .addGroup(createdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createdLayout.createSequentialGroup()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 2133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        createdLayout.setVerticalGroup(
            createdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(createdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Contenedor.addTab("Agendar Cita", created);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel23.setText("Número de cédula del Paciente");

        btnBuscaActualizar.setBackground(new java.awt.Color(51, 153, 255));
        btnBuscaActualizar.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnBuscaActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscaActualizar.setText("Buscar");
        btnBuscaActualizar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBuscaActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel23)
                        .addGap(27, 27, 27)
                        .addComponent(txtCedulaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnBuscaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtCedulaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnBuscaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 390, 120));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        lblActual.setText("Fecha Actual");

        lblNuevo.setText("Fecha Nuevo");

        txtActualHora.setEditable(false);

        lblActual1.setText("Hora Nueva");

        lblActual2.setText("Hora Actual");

        txtFechaActual.setEditable(false);

        cbmNuevaHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActual2)
                    .addComponent(lblActual)
                    .addComponent(lblNuevo)
                    .addComponent(lblActual1))
                .addGap(110, 110, 110)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaNueva, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtActualHora)
                    .addComponent(cbmNuevaHora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaActual))
                .addGap(34, 34, 34))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActual))
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNuevo)
                    .addComponent(FechaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActual2)
                    .addComponent(txtActualHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmNuevaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActual1))
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 420, 180));

        btnActualizar.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizar.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 100, 30));

        citasPacienteU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        citasPacienteU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                citasPacienteUMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(citasPacienteU);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 470, 180));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/fondov4.jpg"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 710));

        Contenedor.addTab("Actualizar Fecha y Hora", jPanel2);

        CONSULTAR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel13.setText("Número de cédula del Paciente");

        btnRegistrar1.setBackground(new java.awt.Color(51, 153, 255));
        btnRegistrar1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnRegistrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar1.setText("Consultar");
        btnRegistrar1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(27, 27, 27)
                .addComponent(txtCedulaConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCedulaConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CONSULTAR.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 390, 110));

        citasPacienteC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        citasPacienteC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                citasPacienteCMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(citasPacienteC);

        CONSULTAR.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 540, 150));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/fondov4.jpg"))); // NOI18N
        CONSULTAR.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 710));

        Contenedor.addTab("Consultar Citas Paciente", CONSULTAR);

        LISTA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnBuscaListado.setBackground(new java.awt.Color(51, 153, 255));
        btnBuscaListado.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnBuscaListado.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscaListado.setText("Buscar");
        btnBuscaListado.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBuscaListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaListadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha Fin");

        jLabel7.setText("Fecha Inicio");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(51, 51, 51)
                        .addComponent(FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addComponent(btnBuscaListado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addComponent(FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FechaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnBuscaListado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LISTA.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 560, 110));

        Listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Listado);

        LISTA.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 640, 230));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/fondov4.jpg"))); // NOI18N
        LISTA.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 710));

        Contenedor.addTab("Consultar Citas", null, LISTA, "");

        DELETE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel26.setText("Número de cédula del Paciente");

        btnBuscaActualizar1.setBackground(new java.awt.Color(51, 153, 255));
        btnBuscaActualizar1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnBuscaActualizar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscaActualizar1.setText("Buscar");
        btnBuscaActualizar1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBuscaActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel26)
                        .addGap(27, 27, 27)
                        .addComponent(txtCedulaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnBuscaActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtCedulaDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscaActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DELETE.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 380, 100));

        pacienteCitaD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        pacienteCitaD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pacienteCitaDMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(pacienteCitaD);

        DELETE.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 500, 150));

        btnEliminar.setBackground(new java.awt.Color(51, 153, 255));
        btnEliminar.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        DELETE.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 100, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/fondov4.jpg"))); // NOI18N
        DELETE.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 710));

        Contenedor.addTab("Eliminar Cita", DELETE);

        add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1844, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:

        if (!txtCedulaC.getText().isBlank()&& !txtNombresC.getText().isBlank() && !txtApellidoCR.getText().isBlank()
                && cbmHora.getSelectedIndex() != -1 && cbmMedicos.getSelectedIndex() != -1){
                dateFormat = new SimpleDateFormat("dd/MM/yyyy"); //transforma la fecha selecionada en en formato dd/mm/aaaa
            try {
                 
                Validaciones.validarCedula(txtCedulaC.getText());
                Validaciones.validarNombre(txtNombresC.getText());
                Validaciones.validarNombre(txtApellidoCR.getText()); 
                java.util.Date fechaUtil = Fecha.getDate();
                Validaciones.validarFecha(Fecha.getDate());
// Convertir la fecha de java.util.Date a java.sql.Date
                java.sql.Date fechaSQL = new java.sql.Date(fechaUtil.getTime());
                cita = new Cita(txtCedulaC.getText(),txtNombresC.getText(),txtApellidoCR.getText(),
                    cbmEspecialidades.getSelectedItem().toString(),medicos.get(cbmMedicos.getSelectedItem()),
                    fechaSQL,cbmHora.getSelectedItem().toString());    
                horas.remove(cbmHora.getSelectedItem().toString());
                conexion.postCita(cita);
                JOptionPane.showMessageDialog(null, "La cita médica ha sido agendada.", "Registrado",JOptionPane.INFORMATION_MESSAGE);
                txtCedulaC.setText("");
                txtNombresC.setText("");
                txtApellidoCR.setText("");
            } catch (ErrorValidaciones | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Registro", HEIGHT);
            }  
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese todos los campos.", "Error Campos", HEIGHT);
        }

    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnBuscaActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActualizarActionPerformed
        // TODO add your handling code here:
        if (!txtCedulaUpdate.getText().isBlank()){
            try{
                Validaciones.validarCedula(txtCedulaUpdate.getText());
                if (!conexion.verificarCita(txtCedulaUpdate.getText())){
                    throw new ErrorValidaciones("No existen citas agendadas al paciente");
                }
                model.setRowCount(0);
                citas = conexion.consultarCitasPaciente(txtCedulaUpdate.getText());
                //System.out.println(citas.toArray().length);
                for (Cita cita : citas){
                    Object[] fila = {cita.getCodigo(),cita.getNombres(),cita.getApellidos(), cita.getFecha(),cita.getHora(),cita.getMedico()};
                    model.addRow(fila);
                }    
            }catch (ErrorValidaciones | SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Consulta", HEIGHT);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese el número de cédula", "Error", HEIGHT);
        }
    }//GEN-LAST:event_btnBuscaActualizarActionPerformed

    private void btnBuscaListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaListadoActionPerformed
        // TODO add your handling code here:
            try{
                model4.setRowCount(0);
                java.util.Date fechaUtil = FechaInicio.getDate();
                java.util.Date fechaUtil2 = FechaFin.getDate();
                // Convertir la fecha de java.util.Date a java.sql.Date
                
                java.sql.Date fechaSQL = new java.sql.Date(fechaUtil.getTime());
                java.sql.Date fechaSQL2 = new java.sql.Date(fechaUtil.getTime());                
                citas = conexion.consultarListaDeCitas(fechaSQL, fechaSQL2);
                for (Cita cita : citas){
                    Object[] fila = {cita.getCodigo(),cita.getNombres(),cita.getApellidos(), cita.getFecha(),cita.getHora(),cita.getMedico()};
                    model4.addRow(fila);
                }
                
            }catch (ErrorValidaciones | SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Consulta", HEIGHT);
            }
                
    }//GEN-LAST:event_btnBuscaListadoActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        // TODO add your handling code here:
        if (!txtCedulaConsult.getText().isBlank()){
            try{
                Validaciones.validarCedula(txtCedulaConsult.getText());
                if (!conexion.verificarCita(txtCedulaConsult.getText())){
                    throw new ErrorValidaciones("No existen citas agendadas al paciente");
                }

                model2.setRowCount(0);
                citas = conexion.consultarCitasPaciente(txtCedulaConsult.getText());
                for (Cita cita : citas){
                    Object[] fila = {cita.getNombres(),cita.getApellidos(), cita.getFecha(),cita.getHora(),cita.getMedico()};
                    model2.addRow(fila);
                } 
            }catch (ErrorValidaciones | SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Registro", HEIGHT);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese el número de cédula", "Error", HEIGHT);
        }        
        
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnBuscaActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActualizar1ActionPerformed
        // TODO add your handling code here:
        if (!txtCedulaDelete.getText().isBlank()){
            try{

                Validaciones.validarCedula(txtCedulaDelete.getText());
                if (!conexion.verificarCita(txtCedulaDelete.getText())){
                    throw new ErrorValidaciones("No existen citas agendadas al paciente");
                }
                model3.setRowCount(0);
                citas = conexion.consultarCitasPaciente(txtCedulaDelete.getText());
                for (Cita cita : citas){
                    Object[] fila = {cita.getCodigo(),cita.getNombres(),cita.getApellidos(), cita.getFecha(),cita.getHora(),cita.getMedico()};
                    model3.addRow(fila);
                }     
            }catch (ErrorValidaciones | SQLException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Registro", HEIGHT);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese el número de cédula", "Error", HEIGHT);
        }          
    }//GEN-LAST:event_btnBuscaActualizar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            conexion.eliminarCita(code);
            JOptionPane.showMessageDialog(null, "La cita médica ha sido eliminada", "Cancelación", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Registro", HEIGHT);
        }    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if (cbmNuevaHora.getSelectedIndex() != -1){
            try {
                Validaciones.validarFecha(FechaNueva.getDate());
                java.util.Date fechaUtil = FechaNueva.getDate();
                java.sql.Date fechaSQL = new java.sql.Date(fechaUtil.getTime());                
                conexion.ActualizarFechayHora(fechaSQL,cbmNuevaHora.getSelectedItem().toString(),code);
                JOptionPane.showMessageDialog(null, "Fecha Actualizada exitosamente.", "Confirmación",JOptionPane.INFORMATION_MESSAGE);
            } catch (ErrorValidaciones | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", HEIGHT);
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbmEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmEspecialidadesActionPerformed
        // TODO add your handling code here:
        cbmMedicos.removeAllItems();
        for (Map.Entry<String, String> entry : especialidad.entrySet()) {
            if (cbmEspecialidades.getSelectedItem().toString().equals(entry.getValue())){
                cbmMedicos.addItem(entry.getKey());
            }
        }           
    }//GEN-LAST:event_cbmEspecialidadesActionPerformed

    private void citasPacienteUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citasPacienteUMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 1){
            Date fechaSQL = (Date) model.getValueAt(citasPacienteU.getSelectedRow(),3); // Cambia la fecha según tus necesidades
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Define el formato deseado
            String fechaFormateada = sdf.format(fechaSQL);
            txtFechaActual.setText(fechaFormateada);
            code = (String) model.getValueAt(citasPacienteU.getSelectedRow(), 0);
            txtActualHora.setText((String) model.getValueAt(citasPacienteU.getSelectedRow(), 4));            
        } 
    }//GEN-LAST:event_citasPacienteUMousePressed


    private void citasPacienteCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citasPacienteCMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_citasPacienteCMousePressed

    private void pacienteCitaDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacienteCitaDMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 1){
            code = (String) model.getValueAt(citasPacienteU.getSelectedRow(), 0);            
        }         
    }//GEN-LAST:event_pacienteCitaDMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONSULTAR;
    private javax.swing.JTabbedPane Contenedor;
    private javax.swing.JPanel DELETE;
    private com.toedter.calendar.JCalendar Fecha;
    private com.toedter.calendar.JDateChooser FechaFin;
    private com.toedter.calendar.JDateChooser FechaInicio;
    private com.toedter.calendar.JDateChooser FechaNueva;
    private javax.swing.JPanel LISTA;
    private javax.swing.JTable Listado;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnBuscaActualizar;
    private javax.swing.JButton btnBuscaActualizar1;
    private javax.swing.JButton btnBuscaListado;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JComboBox<String> cbmEspecialidades;
    private javax.swing.JComboBox<String> cbmHora;
    private javax.swing.JComboBox<String> cbmMedicos;
    private javax.swing.JComboBox<String> cbmNuevaHora;
    private javax.swing.JTable citasPacienteC;
    private javax.swing.JTable citasPacienteU;
    private javax.swing.JPanel created;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblActual;
    private javax.swing.JLabel lblActual1;
    private javax.swing.JLabel lblActual2;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JLabel lblNuevo3;
    private javax.swing.JTable pacienteCitaD;
    private javax.swing.JLabel txt3;
    private javax.swing.JTextField txtActualHora;
    private javax.swing.JTextField txtApellidoCR;
    private javax.swing.JTextField txtCedulaC;
    private javax.swing.JTextField txtCedulaConsult;
    private javax.swing.JTextField txtCedulaDelete;
    private javax.swing.JTextField txtCedulaUpdate;
    private javax.swing.JTextField txtFechaActual;
    private javax.swing.JTextField txtNombresC;
    // End of variables declaration//GEN-END:variables
}
