/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pacientes.extranjeros;

import pacientes.nacionales.*;

/**
 *
 * @author PC
 */
public class ActualizarApellidosExtranjero extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarApellidosNacionales
     */
    public ActualizarApellidosExtranjero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldApellidos = new javax.swing.JTextField();
        txtFieldPasaporte = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        lblPasaporte = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(820, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 61, 200, -1));
        getContentPane().add(txtFieldPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 18, 110, -1));

        lblApellidos.setText("Nuevos apellidos:");
        getContentPane().add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 64, -1, -1));

        lblPasaporte.setText("N° pasaporte: ");
        getContentPane().add(lblPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 21, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 610, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblPasaporte;
    private javax.swing.JTextField txtFieldApellidos;
    private javax.swing.JTextField txtFieldPasaporte;
    // End of variables declaration//GEN-END:variables
}
