/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pacientes.extranjeros;

import pacientes.nacionales.*;

/**
 *
 * @author PC
 */
public class ActualizarEstadoCivilExtranjero extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarEstadoCivilNacional
     */
    public ActualizarEstadoCivilExtranjero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroHC = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        txtFieldNumeroHC = new javax.swing.JTextField();
        cbEstadoCivil = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(820, 640));
        setPreferredSize(new java.awt.Dimension(820, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumeroHC.setText("N° historia clínica: ");
        getContentPane().add(lblNumeroHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 22, -1, -1));

        lblEstadoCivil.setText("Estado civil actualizado: ");
        getContentPane().add(lblEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 69, -1, -1));
        getContentPane().add(txtFieldNumeroHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 19, -1, -1));

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero(a)", "Divorciado(a)", "Unión libre", "Viudo(a)" }));
        getContentPane().add(cbEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 66, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblNumeroHC;
    private javax.swing.JTextField txtFieldNumeroHC;
    // End of variables declaration//GEN-END:variables
}
