/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pacientes.extranjeros;

import pacientes.nacionales.*;

/**
 *
 * @author PC
 */
public class AnamnesisExtranjero extends javax.swing.JInternalFrame {

    /**
     * Creates new form AnamnesisNacional
     */
    public AnamnesisExtranjero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechaInscripcion = new javax.swing.JLabel();
        lblPresion = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblEstatura = new javax.swing.JLabel();
        txtFieldPresion = new javax.swing.JTextField();
        txtFieldTemperatura = new javax.swing.JTextField();
        txtFieldPeso = new javax.swing.JTextField();
        txtFieldEstatura = new javax.swing.JTextField();
        txtFieldFecha = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(820, 640));
        setPreferredSize(new java.awt.Dimension(820, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaInscripcion.setText("Fecha de inscripción: ");
        getContentPane().add(lblFechaInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        lblPresion.setText("Presión: ");
        getContentPane().add(lblPresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        lblTemperatura.setText("Temperatura: ");
        getContentPane().add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        lblPeso.setText("Peso: ");
        getContentPane().add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        lblEstatura.setText("Estatura: ");
        getContentPane().add(lblEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));
        getContentPane().add(txtFieldPresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));
        getContentPane().add(txtFieldTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));
        getContentPane().add(txtFieldPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));
        getContentPane().add(txtFieldEstatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));
        getContentPane().add(txtFieldFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEstatura;
    private javax.swing.JLabel lblFechaInscripcion;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPresion;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JTextField txtFieldEstatura;
    private javax.swing.JTextField txtFieldFecha;
    private javax.swing.JTextField txtFieldPeso;
    private javax.swing.JTextField txtFieldPresion;
    private javax.swing.JTextField txtFieldTemperatura;
    // End of variables declaration//GEN-END:variables
}
