/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pacientes.extranjeros;

import pacientes.nacionales.*;

/**
 *
 * @author PC
 */
public class ContactoReferenciaExtranjero extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContactoReferencia
     */
    public ContactoReferenciaExtranjero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblParentesco = new javax.swing.JLabel();
        txtFieldNombres = new javax.swing.JTextField();
        txtFieldApellidos = new javax.swing.JTextField();
        txtFieldTelefono = new javax.swing.JTextField();
        txtFieldParentesco = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(820, 640));
        setPreferredSize(new java.awt.Dimension(820, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombres.setText("Nombres: ");
        getContentPane().add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 37, -1, -1));

        lblApellidos.setText("Apellidos: ");
        getContentPane().add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 85, -1, -1));

        lblTelefono.setText("Número de teléfono móvil:  ");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 133, -1, -1));

        lblParentesco.setText("Parentesco: ");
        getContentPane().add(lblParentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 181, -1, -1));
        getContentPane().add(txtFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 34, 164, -1));
        getContentPane().add(txtFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 82, 164, -1));

        txtFieldTelefono.setText("09");
        getContentPane().add(txtFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 130, 164, -1));
        getContentPane().add(txtFieldParentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 178, 164, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblParentesco;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtFieldApellidos;
    private javax.swing.JTextField txtFieldNombres;
    private javax.swing.JTextField txtFieldParentesco;
    private javax.swing.JTextField txtFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
