/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pacientes.extranjeros;

import pacientes.nacionales.*;

/**
 *
 * @author PC
 */
public class InformacionPersonalExtranjero extends javax.swing.JInternalFrame {

    /**
     * Creates new form InformacionPersonalNacio
     */
    public InformacionPersonalExtranjero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPasaporte = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefonoMovil = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblTrabajo = new javax.swing.JLabel();
        lblTipoSangre = new javax.swing.JLabel();
        lblSituacionEconomica = new javax.swing.JLabel();
        lblCorreoElectronico = new javax.swing.JLabel();
        txtFieldCedula = new javax.swing.JTextField();
        txtFieldNombres = new javax.swing.JTextField();
        txtFieldApellidos = new javax.swing.JTextField();
        txtFieldDireccion = new javax.swing.JTextField();
        txtFieldTelefono = new javax.swing.JTextField();
        txtFieldEdad = new javax.swing.JTextField();
        txtFieldSituacion = new javax.swing.JTextField();
        txtFieldTrabajo = new javax.swing.JTextField();
        rdBtnFemenino = new javax.swing.JRadioButton();
        rdBtnMasculino = new javax.swing.JRadioButton();
        txtFieldCorreo = new javax.swing.JTextField();
        cbxTipoSangre = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(820, 640));
        setPreferredSize(new java.awt.Dimension(820, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPasaporte.setText("N° pasaporte: ");
        getContentPane().add(lblPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 33, -1, -1));

        lblNombres.setText("Nombres: ");
        getContentPane().add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        lblApellidos.setText("Apellidos: ");
        getContentPane().add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        lblDireccion.setText("Dirección domiciliaria: ");
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        lblTelefonoMovil.setText("N° teléfono móvil: ");
        getContentPane().add(lblTelefonoMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        lblEdad.setText("Edad: ");
        getContentPane().add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        lblSexo.setText("Sexo: ");
        getContentPane().add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 312, -1, -1));

        lblTrabajo.setText("Tipo de trabajo: ");
        getContentPane().add(lblTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 412, -1, -1));

        lblTipoSangre.setText("Tipo de sangre: ");
        getContentPane().add(lblTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 452, -1, -1));

        lblSituacionEconomica.setText("Situación económica: ");
        getContentPane().add(lblSituacionEconomica, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        lblCorreoElectronico.setText("Correo electrónico: ");
        getContentPane().add(lblCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, -1));
        getContentPane().add(txtFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 30, 102, -1));
        getContentPane().add(txtFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 202, -1));
        getContentPane().add(txtFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 200, -1));
        getContentPane().add(txtFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 200, -1));

        txtFieldTelefono.setText("09");
        getContentPane().add(txtFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 90, -1));
        getContentPane().add(txtFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 34, -1));
        getContentPane().add(txtFieldSituacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 110, -1));
        getContentPane().add(txtFieldTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 412, 110, -1));

        rdBtnFemenino.setText("Femenino");
        getContentPane().add(rdBtnFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 310, -1, -1));

        rdBtnMasculino.setText("Masculino");
        getContentPane().add(rdBtnMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 310, -1, -1));
        getContentPane().add(txtFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 110, -1));

        cbxTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-\t", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        getContentPane().add(cbxTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 452, -1, -1));

        jLabel1.setText("Estado Civil: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 352, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero(a)", "Divorciado(a)", "Unión libre", "Viudo(a)" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 349, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 610, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTipoSangre;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPasaporte;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSituacionEconomica;
    private javax.swing.JLabel lblTelefonoMovil;
    private javax.swing.JLabel lblTipoSangre;
    private javax.swing.JLabel lblTrabajo;
    private javax.swing.JRadioButton rdBtnFemenino;
    private javax.swing.JRadioButton rdBtnMasculino;
    private javax.swing.JTextField txtFieldApellidos;
    private javax.swing.JTextField txtFieldCedula;
    private javax.swing.JTextField txtFieldCorreo;
    private javax.swing.JTextField txtFieldDireccion;
    private javax.swing.JTextField txtFieldEdad;
    private javax.swing.JTextField txtFieldNombres;
    private javax.swing.JTextField txtFieldSituacion;
    private javax.swing.JTextField txtFieldTelefono;
    private javax.swing.JTextField txtFieldTrabajo;
    // End of variables declaration//GEN-END:variables
}
