/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacientes;

import interfacesPrincipales.Menu;
import interfacesPrincipales.SGP_MEDSC;
import pacientes.extranjeros.HistoriaClinicaExtranjero;
import pacientes.extranjeros.EnfermedadPreexistenteExtranjero;
import pacientes.extranjeros.AnamnesisExtranjero;
import pacientes.extranjeros.ConsultarCorreoEdadTelefonoSangreExtranjero;
import pacientes.extranjeros.ActualizarMovilExtranjero;
import pacientes.extranjeros.ActualizarEstadoCivilExtranjero;
import pacientes.extranjeros.InformacionPersonalExtranjero;
import pacientes.extranjeros.ActualizarDireccionExtranjero;
import pacientes.extranjeros.ActualizarApellidosExtranjero;
import pacientes.extranjeros.ActualizarNombresExtranjero;
import pacientes.extranjeros.ContactoReferenciaExtranjero;
import pacientes.extranjeros.ConsultarContactoExtranjero;
import pacientes.extranjeros.ConsultarHistoriaClinicaExtranjero;
import pacientes.extranjeros.ActualizarNumeroPasaporte;
import pacientes.extranjeros.ConsultarPacienteExtranjero;

/**
 *
 * @author PC
 */
public class PacienteExtranjero extends javax.swing.JFrame {

    /**
     * Creates new form PacienteExtranjero
     */
    public PacienteExtranjero() {
        initComponents();
        this.setTitle("PACIENTES NACIONALES");
        this.setLocationRelativeTo(null);
        String user = " ";
        user = Menu.jtf;

        if ("grupo1admin".equals(user)) {
            imNombres.setVisible(true);
            imApellidos.setVisible(true);
            imPasaporte_a.setVisible(true);
        } else {
            imNombres.setVisible(false);
            imApellidos.setVisible(false);
            imPasaporte_a.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnRegistrar = new javax.swing.JMenu();
        imInformacionPersonal = new javax.swing.JMenuItem();
        imAnamnesis = new javax.swing.JMenuItem();
        imEnfermedadPreexistente = new javax.swing.JMenuItem();
        imContactoReferencia = new javax.swing.JMenuItem();
        imHistoriaClínica = new javax.swing.JMenuItem();
        mnActualizar = new javax.swing.JMenu();
        imTelefonoMovil_a = new javax.swing.JMenuItem();
        imDireccion_a = new javax.swing.JMenuItem();
        imEstadoCivil_a = new javax.swing.JMenuItem();
        imNombres = new javax.swing.JMenuItem();
        imApellidos = new javax.swing.JMenuItem();
        imPasaporte_a = new javax.swing.JMenuItem();
        mnConsultar = new javax.swing.JMenu();
        imCorreoElectronico_c = new javax.swing.JMenuItem();
        imEdad_c = new javax.swing.JMenuItem();
        imTelefonoMovil_c = new javax.swing.JMenuItem();
        imTipoSangre_c = new javax.swing.JMenuItem();
        imContactoReferencia_c = new javax.swing.JMenuItem();
        imEnfermedadPreexistente_c = new javax.swing.JMenuItem();
        imHistoriaClinica_c = new javax.swing.JMenuItem();
        imPaciente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 700, -1, -1));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 640));

        jMenuBar1.setMaximumSize(new java.awt.Dimension(820, 780));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(820, 780));
        jMenuBar1.setName(""); // NOI18N

        mnRegistrar.setText("Registrar");

        imInformacionPersonal.setText("Información personal");
        imInformacionPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imInformacionPersonalActionPerformed(evt);
            }
        });
        mnRegistrar.add(imInformacionPersonal);

        imAnamnesis.setText("Anamnesis");
        imAnamnesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imAnamnesisActionPerformed(evt);
            }
        });
        mnRegistrar.add(imAnamnesis);

        imEnfermedadPreexistente.setText("Enfermedad preexistente");
        imEnfermedadPreexistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imEnfermedadPreexistenteActionPerformed(evt);
            }
        });
        mnRegistrar.add(imEnfermedadPreexistente);

        imContactoReferencia.setText("Contacto de referencia");
        imContactoReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imContactoReferenciaActionPerformed(evt);
            }
        });
        mnRegistrar.add(imContactoReferencia);

        imHistoriaClínica.setText("Historia Clínica");
        imHistoriaClínica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imHistoriaClínicaActionPerformed(evt);
            }
        });
        mnRegistrar.add(imHistoriaClínica);

        jMenuBar1.add(mnRegistrar);

        mnActualizar.setText("Actualizar");

        imTelefonoMovil_a.setText("número de teléfono móvil");
        imTelefonoMovil_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imTelefonoMovil_aActionPerformed(evt);
            }
        });
        mnActualizar.add(imTelefonoMovil_a);

        imDireccion_a.setText("dirección domiciliaria");
        imDireccion_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imDireccion_aActionPerformed(evt);
            }
        });
        mnActualizar.add(imDireccion_a);

        imEstadoCivil_a.setText("estado civíl");
        imEstadoCivil_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imEstadoCivil_aActionPerformed(evt);
            }
        });
        mnActualizar.add(imEstadoCivil_a);

        imNombres.setText("nombres completos");
        imNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imNombresActionPerformed(evt);
            }
        });
        mnActualizar.add(imNombres);

        imApellidos.setText("apellidos completos");
        imApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imApellidosActionPerformed(evt);
            }
        });
        mnActualizar.add(imApellidos);

        imPasaporte_a.setText("número de pasaporte");
        imPasaporte_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imPasaporte_aActionPerformed(evt);
            }
        });
        mnActualizar.add(imPasaporte_a);

        jMenuBar1.add(mnActualizar);

        mnConsultar.setText("Consultar");

        imCorreoElectronico_c.setText("correo electrónico");
        imCorreoElectronico_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCorreoElectronico_cActionPerformed(evt);
            }
        });
        mnConsultar.add(imCorreoElectronico_c);

        imEdad_c.setText("edad");
        imEdad_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imEdad_cActionPerformed(evt);
            }
        });
        mnConsultar.add(imEdad_c);

        imTelefonoMovil_c.setText("número de teléfono móvil");
        imTelefonoMovil_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imTelefonoMovil_cActionPerformed(evt);
            }
        });
        mnConsultar.add(imTelefonoMovil_c);

        imTipoSangre_c.setText("tipo de sangre");
        imTipoSangre_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imTipoSangre_cActionPerformed(evt);
            }
        });
        mnConsultar.add(imTipoSangre_c);

        imContactoReferencia_c.setText("contacto de referencia");
        imContactoReferencia_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imContactoReferencia_cActionPerformed(evt);
            }
        });
        mnConsultar.add(imContactoReferencia_c);

        imEnfermedadPreexistente_c.setText("enfermedad preexistente");
        imEnfermedadPreexistente_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imEnfermedadPreexistente_cActionPerformed(evt);
            }
        });
        mnConsultar.add(imEnfermedadPreexistente_c);

        imHistoriaClinica_c.setText("historia clínica");
        imHistoriaClinica_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imHistoriaClinica_cActionPerformed(evt);
            }
        });
        mnConsultar.add(imHistoriaClinica_c);

        imPaciente.setText("paciente");
        imPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imPacienteActionPerformed(evt);
            }
        });
        mnConsultar.add(imPaciente);

        jMenuBar1.add(mnConsultar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        SGP_MEDSC sgci = new SGP_MEDSC();
        sgci.getClass();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void imInformacionPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imInformacionPersonalActionPerformed
        InformacionPersonalExtranjero ipextranjero = new InformacionPersonalExtranjero();
        jDesktopPane1.add(ipextranjero);
        ipextranjero.setVisible(true);
    }//GEN-LAST:event_imInformacionPersonalActionPerformed

    private void imAnamnesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imAnamnesisActionPerformed
        AnamnesisExtranjero amExtranjero = new AnamnesisExtranjero();
        jDesktopPane1.add(amExtranjero);
        amExtranjero.setVisible(true);
    }//GEN-LAST:event_imAnamnesisActionPerformed

    private void imEnfermedadPreexistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imEnfermedadPreexistenteActionPerformed
        EnfermedadPreexistenteExtranjero epExtranjero = new EnfermedadPreexistenteExtranjero();
        jDesktopPane1.add(epExtranjero);
        epExtranjero.setVisible(true);
    }//GEN-LAST:event_imEnfermedadPreexistenteActionPerformed

    private void imContactoReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imContactoReferenciaActionPerformed
        ContactoReferenciaExtranjero crExtranjero = new ContactoReferenciaExtranjero();
        jDesktopPane1.add(crExtranjero);
        crExtranjero.setVisible(true);
    }//GEN-LAST:event_imContactoReferenciaActionPerformed

    private void imHistoriaClínicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imHistoriaClínicaActionPerformed
        HistoriaClinicaExtranjero hcExtranjero = new HistoriaClinicaExtranjero();
        hcExtranjero.setVisible(true);
    }//GEN-LAST:event_imHistoriaClínicaActionPerformed

    private void imTelefonoMovil_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imTelefonoMovil_aActionPerformed
        ActualizarMovilExtranjero mExtranjero = new ActualizarMovilExtranjero();
        jDesktopPane1.add(mExtranjero);
        mExtranjero.setVisible(true);
    }//GEN-LAST:event_imTelefonoMovil_aActionPerformed

    private void imDireccion_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imDireccion_aActionPerformed
        ActualizarDireccionExtranjero dExtranjero = new ActualizarDireccionExtranjero();
        jDesktopPane1.add(dExtranjero);
        dExtranjero.setVisible(true);
    }//GEN-LAST:event_imDireccion_aActionPerformed

    private void imEstadoCivil_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imEstadoCivil_aActionPerformed
        ActualizarEstadoCivilExtranjero ecExtranjero = new ActualizarEstadoCivilExtranjero();
        jDesktopPane1.add(ecExtranjero);
        ecExtranjero.setVisible(true);
    }//GEN-LAST:event_imEstadoCivil_aActionPerformed

    private void imCorreoElectronico_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCorreoElectronico_cActionPerformed
        ConsultarCorreoEdadTelefonoSangreExtranjero cetsExtranjero = new ConsultarCorreoEdadTelefonoSangreExtranjero();
        jDesktopPane1.add(cetsExtranjero);
        cetsExtranjero.setVisible(true);
    }//GEN-LAST:event_imCorreoElectronico_cActionPerformed

    private void imEdad_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imEdad_cActionPerformed
        ConsultarCorreoEdadTelefonoSangreExtranjero cetsExtranjero = new ConsultarCorreoEdadTelefonoSangreExtranjero();
        jDesktopPane1.add(cetsExtranjero);
        cetsExtranjero.setVisible(true);
    }//GEN-LAST:event_imEdad_cActionPerformed

    private void imTelefonoMovil_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imTelefonoMovil_cActionPerformed
        ConsultarCorreoEdadTelefonoSangreExtranjero cetsExtranjero = new ConsultarCorreoEdadTelefonoSangreExtranjero();
        jDesktopPane1.add(cetsExtranjero);
        cetsExtranjero.setVisible(true);
    }//GEN-LAST:event_imTelefonoMovil_cActionPerformed

    private void imContactoReferencia_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imContactoReferencia_cActionPerformed
        ConsultarContactoExtranjero ctsExtranjero = new ConsultarContactoExtranjero();
        ctsExtranjero.setVisible(true);
    }//GEN-LAST:event_imContactoReferencia_cActionPerformed

    private void imEnfermedadPreexistente_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imEnfermedadPreexistente_cActionPerformed
        ConsultarContactoExtranjero ctsExtranjero = new ConsultarContactoExtranjero();
        ctsExtranjero.setVisible(true);
    }//GEN-LAST:event_imEnfermedadPreexistente_cActionPerformed

    private void imTipoSangre_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imTipoSangre_cActionPerformed
        ConsultarCorreoEdadTelefonoSangreExtranjero cetsExtranjero = new ConsultarCorreoEdadTelefonoSangreExtranjero();
        jDesktopPane1.add(cetsExtranjero);
        cetsExtranjero.setVisible(true);
    }//GEN-LAST:event_imTipoSangre_cActionPerformed

    private void imHistoriaClinica_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imHistoriaClinica_cActionPerformed
        ConsultarHistoriaClinicaExtranjero chcExtranjero = new ConsultarHistoriaClinicaExtranjero();
        chcExtranjero.setVisible(true);
    }//GEN-LAST:event_imHistoriaClinica_cActionPerformed

    private void imNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imNombresActionPerformed
        ActualizarNombresExtranjero nExtranjero = new ActualizarNombresExtranjero();
        jDesktopPane1.add(nExtranjero);
        nExtranjero.setVisible(true);
    }//GEN-LAST:event_imNombresActionPerformed

    private void imApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imApellidosActionPerformed
        ActualizarApellidosExtranjero aExtranjero = new ActualizarApellidosExtranjero();
        jDesktopPane1.add(aExtranjero);
        aExtranjero.setVisible(true);
    }//GEN-LAST:event_imApellidosActionPerformed

    private void imPasaporte_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imPasaporte_aActionPerformed
        ActualizarNumeroPasaporte aPasaporte = new ActualizarNumeroPasaporte();
        jDesktopPane1.add(aPasaporte);
        aPasaporte.setVisible(true);
    }//GEN-LAST:event_imPasaporte_aActionPerformed

    private void imPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imPacienteActionPerformed
        ConsultarPacienteExtranjero pej = new ConsultarPacienteExtranjero();
        pej.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteExtranjero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteExtranjero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteExtranjero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteExtranjero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteExtranjero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JMenuItem imAnamnesis;
    private javax.swing.JMenuItem imApellidos;
    private javax.swing.JMenuItem imContactoReferencia;
    private javax.swing.JMenuItem imContactoReferencia_c;
    private javax.swing.JMenuItem imCorreoElectronico_c;
    private javax.swing.JMenuItem imDireccion_a;
    private javax.swing.JMenuItem imEdad_c;
    private javax.swing.JMenuItem imEnfermedadPreexistente;
    private javax.swing.JMenuItem imEnfermedadPreexistente_c;
    private javax.swing.JMenuItem imEstadoCivil_a;
    private javax.swing.JMenuItem imHistoriaClinica_c;
    private javax.swing.JMenuItem imHistoriaClínica;
    private javax.swing.JMenuItem imInformacionPersonal;
    private javax.swing.JMenuItem imNombres;
    private javax.swing.JMenuItem imPaciente;
    private javax.swing.JMenuItem imPasaporte_a;
    private javax.swing.JMenuItem imTelefonoMovil_a;
    private javax.swing.JMenuItem imTelefonoMovil_c;
    private javax.swing.JMenuItem imTipoSangre_c;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnActualizar;
    private javax.swing.JMenu mnConsultar;
    private javax.swing.JMenu mnRegistrar;
    // End of variables declaration//GEN-END:variables
}
