/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesPacientes;

import interfacesPrincipales.Menu;
import pacientes.nacionales.HistoriaClinicaNacional;
import pacientes.nacionales.EnfermedadPreexistenteNacional;
import pacientes.nacionales.AnamnesisNacional;
import pacientes.nacionales.ConsultarCorreoEdadTelefonoSangreNacional;
import pacientes.nacionales.ActualizarMovilNacional;
import pacientes.nacionales.ActualizarEstadoCivilNacional;
import pacientes.nacionales.InformacionPersonalNacional;
import pacientes.nacionales.ActualizarDireccionNacional;
import pacientes.nacionales.ContactoReferenciaNacional;
import interfacesPrincipales.SGP_MEDSC;
import javax.swing.JTextField;
import pacientes.nacionales.ActualizarApellidosNacionales;
import pacientes.nacionales.ActualizarNombresNacionales;
import pacientes.nacionales.ConsultarContactoNacional;
import pacientes.nacionales.ConsultarHistoriaClinicaNacional;
import pacientes.nacionales.ConsultarPacienteNacional;

/**
 *
 * @author PC
 */
public class PacienteNacional extends javax.swing.JFrame {

    /**
     * Creates new form PacienteNacional
     */
    public PacienteNacional() {
        initComponents();
        this.setTitle("PACIENTES NACIONALES");
        this.setLocationRelativeTo(null);
        String user = " ";
        user = Menu.jtf;

        if ("grupo1admin".equals(user)) {
            imNombres.setVisible(true);
            imApellidos.setVisible(true);
        } else {
            imNombres.setVisible(false);
            imApellidos.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnRegistrar = new javax.swing.JMenu();
        imInformacionPersonal = new javax.swing.JMenuItem();
        imEnfermedadPreexistente = new javax.swing.JMenuItem();
        imContactoReferencia = new javax.swing.JMenuItem();
        imHistoriaClinica = new javax.swing.JMenuItem();
        mnActualizar = new javax.swing.JMenu();
        imTelefonoMovil_a = new javax.swing.JMenuItem();
        imDireccion_a = new javax.swing.JMenuItem();
        imEstadoCivil_a = new javax.swing.JMenuItem();
        imNombres = new javax.swing.JMenuItem();
        imApellidos = new javax.swing.JMenuItem();
        mnGenerarHC = new javax.swing.JMenu();
        mnConsultar = new javax.swing.JMenu();
        imHistoriaClinica_c = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, -1, -1));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 640));

        mnRegistrar.setText("Registrar");

        imInformacionPersonal.setText("Información personal");
        imInformacionPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imInformacionPersonalActionPerformed(evt);
            }
        });
        mnRegistrar.add(imInformacionPersonal);

        imEnfermedadPreexistente.setText("Enfermedad preexistente");
        imEnfermedadPreexistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imEnfermedadPreexistenteActionPerformed(evt);
            }
        });
        mnRegistrar.add(imEnfermedadPreexistente);

        imContactoReferencia.setText("Contacto de referencia");
        imContactoReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imContactoReferenciaActionPerformed(evt);
            }
        });
        mnRegistrar.add(imContactoReferencia);

        imHistoriaClinica.setText("Historia Clínica");
        imHistoriaClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imHistoriaClinicaActionPerformed(evt);
            }
        });
        mnRegistrar.add(imHistoriaClinica);

        jMenuBar1.add(mnRegistrar);

        mnActualizar.setText("Actualizar");

        imTelefonoMovil_a.setText("número de teléfono móvil");
        imTelefonoMovil_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imTelefonoMovil_aActionPerformed(evt);
            }
        });
        mnActualizar.add(imTelefonoMovil_a);

        imDireccion_a.setText("dirección domiciliaria");
        imDireccion_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imDireccion_aActionPerformed(evt);
            }
        });
        mnActualizar.add(imDireccion_a);

        imEstadoCivil_a.setText("estado civil");
        imEstadoCivil_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imEstadoCivil_aActionPerformed(evt);
            }
        });
        mnActualizar.add(imEstadoCivil_a);

        imNombres.setText("nombres completos");
        imNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imNombresActionPerformed(evt);
            }
        });
        mnActualizar.add(imNombres);

        imApellidos.setText("apellidos completos");
        imApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imApellidosActionPerformed(evt);
            }
        });
        mnActualizar.add(imApellidos);

        jMenuBar1.add(mnActualizar);

        mnGenerarHC.setText("Generar");
        jMenuBar1.add(mnGenerarHC);

        mnConsultar.setText("Consultar");

        imHistoriaClinica_c.setText("historia clínica");
        imHistoriaClinica_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imHistoriaClinica_cActionPerformed(evt);
            }
        });
        mnConsultar.add(imHistoriaClinica_c);

        jMenuBar1.add(mnConsultar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        SGP_MEDSC sgci = new SGP_MEDSC();
        sgci.getClass();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void imInformacionPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imInformacionPersonalActionPerformed
        InformacionPersonalNacional ipnacional = new InformacionPersonalNacional();
        jDesktopPane1.add(ipnacional);
        ipnacional.setVisible(true);
    }//GEN-LAST:event_imInformacionPersonalActionPerformed

    private void imEnfermedadPreexistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imEnfermedadPreexistenteActionPerformed
        EnfermedadPreexistenteNacional epnacional = new EnfermedadPreexistenteNacional();
        jDesktopPane1.add(epnacional);
        epnacional.setVisible(true);
    }//GEN-LAST:event_imEnfermedadPreexistenteActionPerformed

    private void imContactoReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imContactoReferenciaActionPerformed
        ContactoReferenciaNacional crnacional = new ContactoReferenciaNacional();
        jDesktopPane1.add(crnacional);
        crnacional.setVisible(true);
    }//GEN-LAST:event_imContactoReferenciaActionPerformed

    private void imHistoriaClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imHistoriaClinicaActionPerformed
        HistoriaClinicaNacional hcnacional = new HistoriaClinicaNacional();
        hcnacional.setVisible(true);
    }//GEN-LAST:event_imHistoriaClinicaActionPerformed

    private void imTelefonoMovil_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imTelefonoMovil_aActionPerformed
        ActualizarMovilNacional mnacional = new ActualizarMovilNacional();
        jDesktopPane1.add(mnacional);
        mnacional.setVisible(true);
    }//GEN-LAST:event_imTelefonoMovil_aActionPerformed

    private void imDireccion_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imDireccion_aActionPerformed
        ActualizarDireccionNacional dnacional = new ActualizarDireccionNacional();
        jDesktopPane1.add(dnacional);
        dnacional.setVisible(true);
    }//GEN-LAST:event_imDireccion_aActionPerformed

    private void imEstadoCivil_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imEstadoCivil_aActionPerformed
        ActualizarEstadoCivilNacional ecnacional = new ActualizarEstadoCivilNacional();
        jDesktopPane1.add(ecnacional);
        ecnacional.setVisible(true);
    }//GEN-LAST:event_imEstadoCivil_aActionPerformed

    private void imHistoriaClinica_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imHistoriaClinica_cActionPerformed
        ConsultarHistoriaClinicaNacional chcnacional = new ConsultarHistoriaClinicaNacional();
        chcnacional.setVisible(true);
    }//GEN-LAST:event_imHistoriaClinica_cActionPerformed

    private void imNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imNombresActionPerformed
        ActualizarNombresNacionales nnacional= new ActualizarNombresNacionales();
        jDesktopPane1.add(nnacional);
        nnacional.setVisible(true);
    }//GEN-LAST:event_imNombresActionPerformed

    private void imApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imApellidosActionPerformed
        ActualizarApellidosNacionales anacional= new ActualizarApellidosNacionales();
        jDesktopPane1.add(anacional);
        anacional.setVisible(true);
    }//GEN-LAST:event_imApellidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PacienteNacional().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JMenuItem imApellidos;
    private javax.swing.JMenuItem imContactoReferencia;
    private javax.swing.JMenuItem imDireccion_a;
    private javax.swing.JMenuItem imEnfermedadPreexistente;
    private javax.swing.JMenuItem imEstadoCivil_a;
    private javax.swing.JMenuItem imHistoriaClinica;
    private javax.swing.JMenuItem imHistoriaClinica_c;
    private javax.swing.JMenuItem imInformacionPersonal;
    private javax.swing.JMenuItem imNombres;
    private javax.swing.JMenuItem imTelefonoMovil_a;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnActualizar;
    private javax.swing.JMenu mnConsultar;
    private javax.swing.JMenu mnGenerarHC;
    private javax.swing.JMenu mnRegistrar;
    // End of variables declaration//GEN-END:variables
}
