/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesPacientes;

/**
 *
 * @author PC
 */
public class PacienteExtranjero extends javax.swing.JFrame {

    /**
     * Creates new form PacienteExtranjero
     */
    public PacienteExtranjero() {
        initComponents();
        this.setTitle("PACIENTES NACIONALES");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnRegistrar = new javax.swing.JMenu();
        imInformacionPersonal = new javax.swing.JMenuItem();
        imAnamnesis = new javax.swing.JMenuItem();
        imEnfermedadPreexistente = new javax.swing.JMenuItem();
        imContactoReferencia = new javax.swing.JMenuItem();
        imAntecedentesFamiliares = new javax.swing.JMenuItem();
        mnActualizar = new javax.swing.JMenu();
        imTelefonoMovil_a = new javax.swing.JMenuItem();
        imDireccion_a = new javax.swing.JMenuItem();
        imEstadoCivil_a = new javax.swing.JMenuItem();
        imNombres_a = new javax.swing.JMenuItem();
        imApellidos_a = new javax.swing.JMenuItem();
        mnConsultar = new javax.swing.JMenu();
        imCorreoElectronico_c = new javax.swing.JMenuItem();
        imEdad_c = new javax.swing.JMenuItem();
        imTelefonoMovil_c = new javax.swing.JMenuItem();
        imContactoReferencia_c = new javax.swing.JMenuItem();
        imEnfermedadPreexistente_c = new javax.swing.JMenuItem();
        imTipoSangre_c = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(820, 780));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(820, 780));
        jMenuBar1.setName(""); // NOI18N

        mnRegistrar.setText("Registrar");

        imInformacionPersonal.setText("Información personal");
        mnRegistrar.add(imInformacionPersonal);

        imAnamnesis.setText("Anamnesis");
        mnRegistrar.add(imAnamnesis);

        imEnfermedadPreexistente.setText("Enfermedad preexistente");
        mnRegistrar.add(imEnfermedadPreexistente);

        imContactoReferencia.setText("Contacto de referencia");
        mnRegistrar.add(imContactoReferencia);

        imAntecedentesFamiliares.setText("Antecedentes familiares");
        mnRegistrar.add(imAntecedentesFamiliares);

        jMenuBar1.add(mnRegistrar);

        mnActualizar.setText("Actualizar");

        imTelefonoMovil_a.setText("número de teléfono móvil");
        mnActualizar.add(imTelefonoMovil_a);

        imDireccion_a.setText("dirección domiciliaria");
        mnActualizar.add(imDireccion_a);

        imEstadoCivil_a.setText("estado civíl");
        mnActualizar.add(imEstadoCivil_a);

        imNombres_a.setText("nombres completos");
        mnActualizar.add(imNombres_a);

        imApellidos_a.setText("apellidos completos");
        mnActualizar.add(imApellidos_a);

        jMenuBar1.add(mnActualizar);

        mnConsultar.setText("Consultar");

        imCorreoElectronico_c.setText("correo electrónico");
        mnConsultar.add(imCorreoElectronico_c);

        imEdad_c.setText("edad");
        mnConsultar.add(imEdad_c);

        imTelefonoMovil_c.setText("número de teléfono móvil");
        mnConsultar.add(imTelefonoMovil_c);

        imContactoReferencia_c.setText("contacto de referencia");
        mnConsultar.add(imContactoReferencia_c);

        imEnfermedadPreexistente_c.setText("enfermedad preexistente");
        mnConsultar.add(imEnfermedadPreexistente_c);

        imTipoSangre_c.setText("tipo de sangre");
        mnConsultar.add(imTipoSangre_c);

        jMenuBar1.add(mnConsultar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteExtranjero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteExtranjero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteExtranjero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteExtranjero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteExtranjero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imAnamnesis;
    private javax.swing.JMenuItem imAntecedentesFamiliares;
    private javax.swing.JMenuItem imApellidos_a;
    private javax.swing.JMenuItem imContactoReferencia;
    private javax.swing.JMenuItem imContactoReferencia_c;
    private javax.swing.JMenuItem imCorreoElectronico_c;
    private javax.swing.JMenuItem imDireccion_a;
    private javax.swing.JMenuItem imEdad_c;
    private javax.swing.JMenuItem imEnfermedadPreexistente;
    private javax.swing.JMenuItem imEnfermedadPreexistente_c;
    private javax.swing.JMenuItem imEstadoCivil_a;
    private javax.swing.JMenuItem imInformacionPersonal;
    private javax.swing.JMenuItem imNombres_a;
    private javax.swing.JMenuItem imTelefonoMovil_a;
    private javax.swing.JMenuItem imTelefonoMovil_c;
    private javax.swing.JMenuItem imTipoSangre_c;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnActualizar;
    private javax.swing.JMenu mnConsultar;
    private javax.swing.JMenu mnRegistrar;
    // End of variables declaration//GEN-END:variables
}
