/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pacientes.nacionales;

/**
 *
 * @author PC
 */
public class ActualizarNombresNacionales extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarNombresNacionales
     */
    public ActualizarNombresNacionales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCedula = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtFieldCedula = new javax.swing.JTextField();
        txtFieldNombres = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(820, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCedula.setText("CI: ");
        getContentPane().add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 21, -1, -1));

        lblNombres.setText("Nuevos nombres:");
        getContentPane().add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 64, -1, -1));
        getContentPane().add(txtFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 18, 100, -1));
        getContentPane().add(txtFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 61, 200, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 610, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JTextField txtFieldCedula;
    private javax.swing.JTextField txtFieldNombres;
    // End of variables declaration//GEN-END:variables
}
