/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesAtencion;

import interfacesCitas.*;
import interfacesPrincipales.SGP_MEDSC;
import interfacesPrincipales.SGP_MEDSC_admin;

/**
 *
 * @author Usuario
 */
public class AtencionMedica extends javax.swing.JFrame {

    /**
     * Creates new form CitaMédica
     */
    static String parametro;
    public AtencionMedica() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuREGIS = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Consultar = new javax.swing.JMenu();
        telefonoPaciente = new javax.swing.JMenuItem();
        nombresCitas = new javax.swing.JMenuItem();
        fechaCitas = new javax.swing.JMenuItem();
        regresarMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pantalla2Layout = new javax.swing.GroupLayout(pantalla2);
        pantalla2.setLayout(pantalla2Layout);
        pantalla2Layout.setHorizontalGroup(
            pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );
        pantalla2Layout.setVerticalGroup(
            pantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        menuREGIS.setText("Registrar");
        menuREGIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuREGISMouseClicked(evt);
            }
        });

        jMenuItem1.setText("Atención");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuREGIS.add(jMenuItem1);

        jMenuItem2.setText("Orden Médica");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuREGIS.add(jMenuItem2);

        jMenuItem3.setText("Interconsulta");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuREGIS.add(jMenuItem3);

        jMenuItem4.setText("Evolución");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuREGIS.add(jMenuItem4);

        jMenuBar1.add(menuREGIS);

        Consultar.setText("Consultar");

        telefonoPaciente.setText("Cédula Paciente");
        telefonoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoPacienteActionPerformed(evt);
            }
        });
        Consultar.add(telefonoPaciente);

        nombresCitas.setText("Fecha de Atención");
        nombresCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresCitasActionPerformed(evt);
            }
        });
        Consultar.add(nombresCitas);

        fechaCitas.setText("Médico Asignado");
        fechaCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaCitasActionPerformed(evt);
            }
        });
        Consultar.add(fechaCitas);

        jMenuBar1.add(Consultar);

        regresarMenu.setText("Regresar");
        regresarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(regresarMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pantalla2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pantalla2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMenuMouseClicked
        // TODO add your handling code here:
        SGP_MEDSC_admin sgci = new SGP_MEDSC_admin();
        sgci.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarMenuMouseClicked

    private void fechaCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaCitasActionPerformed
        // TODO add your handling code here:
        parametro = "Fecha";
        FormConsultarAtencionMedico formulario = new  FormConsultarAtencionMedico();
        pantalla2.removeAll();
        pantalla2.add(formulario);
        pantalla2.revalidate();
        formulario.setVisible(true);
    }//GEN-LAST:event_fechaCitasActionPerformed

    private void telefonoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoPacienteActionPerformed
        // TODO add your handling code here:
        FormConsultarAtencionPaciente formulario = new  FormConsultarAtencionPaciente();
        pantalla2.removeAll();
        pantalla2.add(formulario);
        pantalla2.revalidate();
        formulario.setVisible(true);
    }//GEN-LAST:event_telefonoPacienteActionPerformed

    private void nombresCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresCitasActionPerformed
        // TODO add your handling code here:
        parametro = "Nombres Paciente";
        FormConsultarAtencionFecha formulario = new  FormConsultarAtencionFecha();
        pantalla2.removeAll();
        pantalla2.add(formulario);
        pantalla2.revalidate();
        formulario.setVisible(true);
    }//GEN-LAST:event_nombresCitasActionPerformed

    private void menuREGISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuREGISMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuREGISMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormularioRegistrosOrden formulario = new FormularioRegistrosOrden();
        pantalla2.removeAll();
        pantalla2.add(formulario);
        pantalla2.revalidate();
        formulario.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormularioRegistrosAtencionPrev formulario = new FormularioRegistrosAtencionPrev(pantalla2);
        pantalla2.removeAll();
        pantalla2.add(formulario);
        pantalla2.revalidate();
        formulario.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FormularioRegistrosInter formulario = new FormularioRegistrosInter();
        pantalla2.removeAll();
        pantalla2.add(formulario);
        pantalla2.revalidate();
        formulario.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FormularioRegistrosEvo formulario = new FormularioRegistrosEvo();
        pantalla2.removeAll();
        pantalla2.add(formulario);
        pantalla2.revalidate();
        formulario.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtencionMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtencionMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtencionMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtencionMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtencionMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Consultar;
    private javax.swing.JMenuItem fechaCitas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu menuREGIS;
    private javax.swing.JMenuItem nombresCitas;
    private javax.swing.JDesktopPane pantalla2;
    private javax.swing.JMenu regresarMenu;
    private javax.swing.JMenuItem telefonoPaciente;
    // End of variables declaration//GEN-END:variables
}
