/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfacesAdministracion;

import interfacesPrincipales.SGP_MEDSC_admin;

/**
 *
 * @author PC
 */
public class AdministracionSistema_ extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdministracionSistema_
     */
    public AdministracionSistema_() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adUsers = new javax.swing.JButton();
        adParams = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(560, 780));
        setMinimumSize(new java.awt.Dimension(560, 780));
        setPreferredSize(new java.awt.Dimension(560, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adUsers.setText("Administración Usuarios");
        adUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adUsersActionPerformed(evt);
            }
        });
        jPanel1.add(adUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 220, 440));

        adParams.setText("Administración Parametros");
        adParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adParamsActionPerformed(evt);
            }
        });
        jPanel1.add(adParams, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 210, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adUsersActionPerformed
        // TODO add your handling code here:
        AdministracionUsuario users = new AdministracionUsuario();
        users.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adUsersActionPerformed

    private void adParamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adParamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adParamsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adParams;
    private javax.swing.JButton adUsers;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
